baseURL = "https://oxsynn.github.io/"
languageCode = "en-us"
title = "Gilbert Cisneros - System Administrator"
theme = "lekh"

[[menu.main]]

[[params.social]]
	
[params.style]
	darkestColor = "#d35050"
	darkColor = "#212121"
	lightColor = "#f5e3e0"
	lightestColor = "#f5f5f5"
	primaryColor = "#fff"

