baseURL = "https://gilbert.oxsynn.com/"
languageCode = "en-us"
title = "Gilbert Cisneros - System Administrator"

theme = "m10c"


[menu]
[[menu.main]]
	identifier = "home"
	name = "Home"
	url = "/"
[[menu.main]]
	identifier = "post"
	name = "Posts"
	url = "/post/"
[[menu.main]]
	identifier = "project"
	name = "Projects"
	url = "/project/"


[params]
	author = "Gilbert Cisneros"
	description = "System Administrator looking to increase his skill set to include Software Dev and Devops"
	
[[params.social]]
	name = "github"
	url = "https://github.com/oxsynn/"

[params.style]
	darkestColor = "#d35050"
	darkColor = "#212121"
	lightColor = "#f5e3e0"
	lightestColor = "#f5f5f5"
	primaryColor = "#fff"
